const serviceData = [
  { id:'exterior', title:'Außenvisualisierung', text:'Realistische Renderings für Architektur, Vermarktung und Projektpräsentation. Wir erstellen hochwertige Außenvisualisierungen von Gebäuden, Objekten und Immobilienprojekten – ideal für Exposés, Websites, Präsentationen und Verkaufsunterlagen.', source:'Ausgang: Plan, Skizze, 3D-Modell oder Referenz', result:'Ergebnis: realistisches Außenrendering', time:'Lieferzeit: ab 4 Stunden / nächster Arbeitstag 7 Uhr', price:'Preis: ab CHF XXX', cta:'Außenvisualisierung anfragen', img:'serviceExteriorResult', sourceImg:'serviceExteriorSource', category:'exterior' },
  { id:'interior-1', title:'Aus 2D-Plan wird ein realistischer Raum', text:'Aus Grundrissen und 2D-Plänen erstellen wir realistische Innenräume mit Einrichtung, Licht, Materialien und Atmosphäre.', source:'Ausgang: 2D-Grundriss', result:'Ergebnis: realistisches Innenraumbild', time:'Lieferzeit: ab 4 Stunden', price:'Preis: ab CHF XXX', cta:'Plan visualisieren lassen', img:'serviceInteriorPlanResult', sourceImg:'serviceInteriorPlanSource', category:'interior' },
  { id:'interior-2', title:'3D-Rendering realistisch veredeln', text:'Wir machen aus bestehenden 3D-Renderings oder Modellen hochwertige, fotorealistische Bilder für Präsentation und Vermarktung.', source:'Ausgang: 3D-Modell oder einfaches Rendering', result:'Ergebnis: fotorealistisches Bild', time:'Lieferzeit: nächster Arbeitstag 7 Uhr', price:'Preis: ab CHF XXX', cta:'Rendering optimieren lassen', img:'serviceInteriorRenderResult', sourceImg:'serviceInteriorRenderSource', category:'interior' },
  { id:'interior-3', title:'Vom Rohbau zum fertigen Innenraum', text:'Wir zeigen, wie ein unfertiger Raum später aussehen könnte – mit Boden, Wänden, Licht, Möbeln und passender Atmosphäre.', source:'Ausgang: Rohbau oder Baustellenfoto', result:'Ergebnis: fertige Innenvisualisierung', time:'Lieferzeit: ab 4 Stunden', price:'Preis: ab CHF XXX', cta:'Rohbau visualisieren lassen', img:'serviceRawResult', sourceImg:'serviceRawSource', category:'interior' },
  { id:'staging-1', title:'Virtual Staging', text:'Wir möblieren leere Räume digital und machen sie wohnlich, hochwertig und verkaufsstark.', source:'Ausgang: leerer Raum', result:'Ergebnis: möblierter Raum', time:'Lieferzeit: ab 4 Stunden', price:'Preis: ab CHF XXX', cta:'Raum möblieren lassen', img:'serviceStagingResult', sourceImg:'serviceStagingSource', category:'staging' },
  { id:'staging-2', title:'Möbel entfernen', text:'Wir entfernen bestehende Möbel, persönliche Gegenstände oder störende Elemente digital und schaffen einen neutralen, sauberen Raum.', source:'Ausgang: möblierter oder überfüllter Raum', result:'Ergebnis: leerer, neutraler Raum', time:'Lieferzeit: ab 4 Stunden', price:'Preis: ab CHF XXX', cta:'Möbel entfernen lassen', img:'serviceRemoveResult', sourceImg:'serviceRemoveSource', category:'staging' },
  { id:'staging-3', title:'Virtuelle Renovation', text:'Wir visualisieren Renovationsideen digital – zum Beispiel neue Dusche, andere Fliesen, neue Böden, Wandfarben oder moderne Materialien.', source:'Ausgang: alter oder renovierungsbedürftiger Raum', result:'Ergebnis: renovierter Raum', time:'Lieferzeit: ab 4 Stunden', price:'Preis: ab CHF XXX', cta:'Renovation visualisieren lassen', img:'serviceRenovationResult', sourceImg:'serviceRenovationSource', category:'staging' }
];
const cases = [
  ['Innenraum','Grundriss zu Wohnraum','2D-Grundriss','realistischer Wohnraum','serviceInteriorPlanSource','serviceInteriorPlanResult'],
  ['Innenraum','Rohbau zu fertigem Innenraum','Rohbau','möblierter Innenraum','serviceRawSource','serviceRawResult'],
  ['Virtual Staging','Leerer Raum zu Verkaufsbild','leerer Raum','möbliertes Inseratsbild','serviceStagingSource','serviceStagingResult'],
  ['Virtual Staging','Möbel entfernen','überfüllter Raum','neutraler leerer Raum','serviceRemoveSource','serviceRemoveResult'],
  ['Renovation','Virtuelle Renovation Bad','altes Bad','modernes Bad','serviceRenovationSource','serviceRenovationResult'],
  ['Außen','Außenrendering Neubau','Plan / Modell','realistisches Außenrendering','serviceExteriorSource','serviceExteriorResult']
].map(([category,title,from,to,before,after], i)=>({id:i,category,title,from,to,before,after}));
const filters=['Alle','Außen','Innenraum','Virtual Staging','Renovation'];

async function init(){const [texts,assets]=await Promise.all([fetch('text.json').then(r=>r.json()),fetch('assets.json').then(r=>r.json())]);
 document.querySelectorAll('[data-text]').forEach(el=>{const k=el.dataset.text;if(texts[k])el.textContent=texts[k]});
 document.querySelectorAll('[data-asset]').forEach(el=>{const k=el.dataset.asset;if(assets[k])el.src=assets[k]});
 renderServices(assets); renderFilters(); renderPortfolio('Alle', assets);
 setupScrollSpy(); setupReveal();
 document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
 document.getElementById('contactForm').onsubmit=(e)=>{e.preventDefault(); if(!e.target.reportValidity())return; e.target.reset(); document.getElementById('formMessage').textContent=texts.contactSuccess;};
}
function renderServices(a){const host=document.getElementById('serviceScenes'); host.innerHTML=serviceData.map(s=>`<article class="scene reveal" id="${s.id}" data-cat="${s.category}"><img class="scene-bg" src="${a[s.img]}" alt="${s.title}"><img class="scene-source" src="${a[s.sourceImg]}" alt="Ausgang für ${s.title}"><div class="scene-card"><h3>${s.title}</h3><p>${s.text}</p><ul><li>${s.source}</li><li>${s.result}</li><li>${s.time}</li><li>${s.price}</li></ul><button class="btn" data-scroll="contact">${s.cta}</button></div></article>`).join('');}
function renderFilters(){const f=document.getElementById('filters');f.innerHTML=filters.map((x,i)=>`<button class="filter-btn ${i===0?'active':''}">${x}</button>`).join(''); f.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{f.querySelectorAll('button').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); fetch('assets.json').then(r=>r.json()).then(a=>renderPortfolio(btn.textContent,a));});}
function renderPortfolio(filter, a){const g=document.getElementById('portfolioGrid');const rows=cases.filter(c=>filter==='Alle'||c.category===filter); g.innerHTML=rows.map(c=>`<article class="p-card" data-id="${c.id}"><img src="${a[c.after]}" alt="${c.title}"><div><small>${c.category}</small><h3>${c.title}</h3><p>Ausgang: ${c.from}<br>Ergebnis: ${c.to}</p></div></article>`).join(''); g.querySelectorAll('.p-card').forEach(card=>card.onclick=()=>openModal(rows.find(x=>x.id==card.dataset.id),a));}
function openModal(c,a){const m=document.getElementById('portfolioModal'); document.getElementById('modalTitle').textContent=c.title; document.getElementById('beforeImg').src=a[c.before]; document.getElementById('afterImg').src=a[c.after]; document.getElementById('modalMeta').textContent=`Ausgangslage: ${c.from} · Ergebnis: ${c.to}`; m.showModal();}
document.getElementById('closeModal').onclick=()=>document.getElementById('portfolioModal').close();
function setupScrollSpy(){const tabs=[...document.querySelectorAll('.tab')]; const map={exterior:['exterior'],interior:['interior-1','interior-2','interior-3'],staging:['staging-1','staging-2','staging-3']}; tabs.forEach(t=>t.onclick=()=>document.getElementById(map[t.dataset.target][0]).scrollIntoView({behavior:'smooth'})); const io=new IntersectionObserver((entries)=>{entries.forEach(e=>{if(!e.isIntersecting)return; const id=e.target.id; const active=tabs.find(t=>map[t.dataset.target].includes(id)); if(active){tabs.forEach(x=>x.classList.remove('is-active')); active.classList.add('is-active');}})},{threshold:.5}); Object.values(map).flat().forEach(id=>io.observe(document.getElementById(id)));}
function setupReveal(){const io=new IntersectionObserver((entries)=>entries.forEach(e=>e.target.classList.toggle('in',e.isIntersecting)),{threshold:.2}); document.querySelectorAll('.reveal').forEach(el=>io.observe(el));}
init();
